# Generated by Django 4.2.6 on 2023-10-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("patronymic", models.CharField(max_length=50)),
                ("birth_date", models.DateField()),
                ("date_of_admission", models.DateField()),
                (
                    "group",
                    models.ManyToManyField(related_name="student", to="group.group"),
                ),
            ],
        ),
    ]
