# Generated by Django 4.2.6 on 2023-10-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0002_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ManyToManyField(related_name="students", to="group.group"),
        ),
    ]
